name: Node.js CI

on:
  push:
    branches:
      - master # Certifique-se de que esse é o nome correto da sua branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Seta o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instala as dependências
        run: npm ci

      - name: Roda os testes
        run: npx jest
