name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.14.0]

    steps:
      - name: Checkout respositorio
        uses: actions/checkout@v3

      - name: Seta o Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instala as dependencias
        run: npm install

      - name: Roda os testes
        run: npx jest
